---
azuracast_www_group: "www-data"
azuracast_www_directories:
  - "{{ azuracast_src_dir }}/frontend/node_modules"
  - "{{ azuracast_src_dir }}/web/static"
  - "{{ azuracast_src_dir }}/web/static/dist"
  - "{{ azuracast_src_dir }}/web/static/webpack_dist"

azuracast_user_password_file: "{{ azuracast_secrets_dir }}/user.password"
azuracast_user_password: "{{ lookup('password', azuracast_user_password_file + ' length=16') }}"

azuracast_mysql_password_file: "{{ azuracast_secrets_dir }}/mysql.password"
azuracast_mysql_password: "{{ lookup('password', azuracast_mysql_password_file + ' length=16') }}"

azuracast_composer_options:
  development: ""
  production: "--no-dev --optimize-autoloader"

azuracast_build_system_packages:
  - nodejs

azuracast_system_packages: >-
  {{
    azuracast_base_system_packages
    + azuracast_icecast_system_packages
    + azuracast_build_system_packages
    + azuracast_liquidsoap_system_packages
    + azuracast_php_sys_packages
    + azuracast_waveform_system_packages
  }}

azuracast_icecast_system_packages:
  - libssl-dev
  - libvorbis-dev
  - libxml2
  - libxslt1-dev
  - pkg-config
# - libcurl4-openssl-dev   # conflicts with libcurl4-gnutls-dev which superseeds this one

azuracast_base_system_packages:
  - beanstalkd
  - cron
  - mariadb-client
  - mariadb-server
  - nginx
  - nginx-common
  - nginx-extras
  - supervisor
  - tmpreaper


azuracast_unwanted_packages:
  - apache2
  - influxdb
  - lighttpd

azuracast_build_node_version: 16
azuracast_build_node_repo: "https://deb.nodesource.com/node_{{ azuracast_build_node_version }}.x"
azuracast_build_node_keyring_url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
azuracast_build_node_keyring_path: "/usr/share/keyrings/nodesource.gpg"

azuracast_external_repository_keys:
  - url: "{{ azuracast_build_node_keyring_url }}"
    keyring: "{{ azuracast_build_node_keyring_path }}"

  - url: "https://supplychain.mariadb.com/mariadb-keyring-2019.gpg"
    keyring: "/etc/apt/trusted.gpg.d/mariadb-keyring-2019.gpg"

azuracast_external_repositories:
  - description: "azuracast radio dependencies"
    repo: "ppa:chris-needham/ppa"

  - description: "azuracast php dependencies"
    repo: "ppa:ondrej/php"

  - description: "Nodejs"
    repo: "deb [signed-by={{ azuracast_build_node_keyring_path }}] {{ azuracast_build_node_repo }} {{ ansible_lsb.codename }} main"
    file: nodejs

  - description: "Nodejs src"
    repo: "deb-src [signed-by={{ azuracast_build_node_keyring_path }}] {{ azuracast_build_node_repo }} {{ ansible_lsb.codename }} main"
    file: nodejs

  - description: "Mariadb"
    repo: "deb [arch=amd64,arm64] https://downloads.mariadb.com/MariaDB/mariadb-10.5/repo/ubuntu {{ ansible_lsb.codename }} main"
    file: mariadb

  - description: "Mariadb debug"
    repo: "deb [arch=amd64,arm64] https://downloads.mariadb.com/MariaDB/mariadb-10.5/repo/ubuntu {{ ansible_lsb.codename }} main/debug"
    file: mariadb

  - description: "Mariadb tools"
    repo: "deb [arch=amd64] http://downloads.mariadb.com/Tools/ubuntu {{ ansible_lsb.codename }} main"
    file: mariadb

azuracast_opam_switch_version: "4.12.0"
azuracast_liquidsoap_system_packages:
  - autoconf
  - automake
  - bubblewrap
  - ffmpeg
  - frei0r-plugins-dev
  - ladspa-sdk
  - libavcodec-dev
  - libavdevice-dev
  - libavfilter-dev
  - libavformat-dev
  - libavresample-dev
  - libavutil-dev
  - libcurl4-gnutls-dev
  - libfaad-dev
  - libfdk-aac-dev
  - libflac-dev
  - libmad0-dev
  - libmp3lame-dev
  - libogg-dev
  - libopus-dev
  - libpcre3-dev
  - libpostproc-dev
  - libsamplerate0-dev
  - libssl-dev
  - libswresample-dev
  - libswscale-dev
  - libtag1-dev
  - libvorbis-dev
  - m4
  - multimedia-audio-plugins
  - ocaml
  - opam
  - pkg-config
  - swh-plugins
  - tap-plugins
  - unzip

azuracast_php_version: "8.1"
azuracast_php_sys_packages:
  - "php{{ azuracast_php_version }}-bcmath"      # BigInteger
  - "php{{ azuracast_php_version }}-cli"
  - "php{{ azuracast_php_version }}-curl"
  - "php{{ azuracast_php_version }}-fpm"
  - "php{{ azuracast_php_version }}-gd"
  - "php{{ azuracast_php_version }}-gmp"         # BigInteger and PHP-IP
  - "php{{ azuracast_php_version }}-intl"        # Localization
  - "php{{ azuracast_php_version }}-maxminddb"   # Maxmind (GeoIP) DB native ext
  - "php{{ azuracast_php_version }}-mbstring"    # Codeception Tests
  - "php{{ azuracast_php_version }}-mysqlnd"     # MySQL Native Driver (Doctrine)
  - "php{{ azuracast_php_version }}-redis"       # Cache
  - "php{{ azuracast_php_version }}-xml"         # IceCast XML config
  - "php{{ azuracast_php_version }}-zip"         # Composer installs

azuracast_waveform_system_packages:
  - audiowaveform
  - flac
  - vorbis-tools
