---
- hosts: localhost
  become: true
  gather_facts: false

  vars:
    app_env: "{{ lookup('env', 'APP_ENV') | default('production', true) }}"
    update_mode: false
    dev_azuracast_user_password: "azuracast"
    dev_mysql_user_password: "azuracast"

  roles:
    - init
    - redis
    - nginx
    - azuracast
