---
- name: (_config) Write environment configuration file
  template:
    src: config/env.ini.j2
    dest: "{{ www_base }}/env.ini"
    owner: "{{ azuracast_user }}"
    group: "{{ azuracast_www_group }}"
    mode: 0644
    force: false

- name: (_config) Set up environment file
  ini_file:
    dest: "{{ www_base }}/env.ini"
    section: "configuration"
    option: "application_env"
    value: "{{ azuracast_app_env }}"
    mode: 0644

- name: (_config) Set Permissions on Base App Folder
  file:
    path: "{{ app_base }}"
    state: directory
    owner: "{{ azuracast_user }}"
    group: "{{ azuracast_www_group }}"
    mode: 0775

- name: (_config) Clear temp directory
  file:
    path: "{{ tmp_base }}"
    state: absent

- name: (_config) Create System Folders
  file:
    path: "{{ _current_directory }}"
    state: directory
    owner: "{{ azuracast_user }}"
    group: "{{ azuracast_www_group }}"
    mode: 0775
  loop:
    - "{{ tmp_base }}"
    - "{{ tmp_base }}/proxies"
    - "{{ app_base }}/stations"
    - "{{ app_base }}/geoip"
    - "{{ app_base }}/dbip"
    - "{{ app_base }}/backups"
    - "{{ app_base }}/servers"
    - "{{ app_base }}/servers/shoutcast2"
    - "{{ app_base }}/servers/icecast2"
    - "{{ app_base }}/uploads"
  loop_control:
    loop_var: _current_directory
