---

- name: Configure PHP FPM Pool
  template:
    src: fpmpool.j2
    dest: "/etc/php/{{ azuracast_php_version }}/fpm/pool.d/www.conf"
    force: true
    mode: 0644

- name: Configure php-fpm php.ini
  ini_file:
    dest: "/etc/php/{{ azuracast_php_version }}/fpm/php.ini"
    section: PHP
    option: "{{ _current_php_init_option.option }}"
    value: "{{ _current_php_init_option.value }}"
    mode: 0644
  loop:
    - option: "post_max_size"
      value: "50M"
    - option: "short_open_tag"
      value: "On"
    - option: "upload_max_filesize"
      value: "50M"
  loop_control:
    loop_var: _current_php_init_option

- name: Configure php-cli php.ini
  ini_file:
    dest: "/etc/php/{{ azuracast_php_version }}/cli/php.ini"
    section: PHP
    option: "short_open_tag"
    value: "On"
    mode: 0644

- name: Enable php-fpm service
  systemd:
    name: php{{ azuracast_php_version }}-fpm
    state: started
    enabled: true
