---
- name: Change supervisord configuration
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisor/supervisord.conf
    force: true
    mode: 0644
  notify: Restart supervisor

- name: Remove old core supervisord configuration
  file:
    path: /etc/supervisor/conf.d/core.conf
    state: absent
  notify: Restart supervisor

- name: Enable supervisor
  service:
    name: supervisor
    enabled: true
    state: started
