---
init_supported_architecture:
  - i386
  - x86_64
init_supported_os:
  - distribution_release: "focal"
    version: "20.04"

init_system_packages:
  - apt-transport-https
  - build-essential
  - curl
  - git
  - gzip
  - pwgen
  - python3
  - python3-pip
  - python3-pymysql
  - python3-setuptools
  - python3-venv
  - python3-wheel
  - software-properties-common
  - tar
  - unzip
  - wget
  - whois
  - zip
  - zstd
