---
- name: Build Icecast
  include_tasks: icecast.yml

- name: Install Liquidsoap
  include_tasks: liquidsoap.yml

- name: Install Audiowaveform
  apt:
    name: audiowaveform
    install_recommends: false

- name: Install Flac
  apt:
    name: flac
    install_recommends: false

- name: Install Vorbis-Tools
  apt:
    name: vorbis-tools
    install_recommends: false
